import { lazy } from "react";

export const ModuleErrorBoundary = lazy(() => import("../ModuleErrorBoundary"));
export const DatePickerInput = lazy(() => import("../DatePickerInput"));
export const YeastarSoftphone = lazy(() => import("../YeastarSoftphone"));
export const RealtimeMonitoringDashboard = lazy(() => import("../RealtimeMonitoringDashboard"));
export const EnhancedStatisticsView = lazy(() => import("../EnhancedStatisticsView").then(m => ({ default: m.EnhancedStatisticsView })));
export const DossierBrainCenter = lazy(() => import("../DossierBrainCenter"));
export const ContractsView = lazy(() => import("../ContractsView"));
export const CustomCalendar = lazy(() => import("../CustomCalendar"));
export const ERPRecordCaseDetails = lazy(() => import("./ERPRecordCaseDetails"));
export const SpecializedRecordsView = lazy(() => import("../../modules/SpecializedRecords/SpecializedRecordsView"));
export const RecycleBinView = lazy(() => import("../RecycleBinView").then(m => ({ default: m.RecycleBinView })));
export const ActivityLogsView = lazy(() => import("../ActivityLogsView").then(m => ({ default: m.ActivityLogsView })));
export const ERPRecordFilters = lazy(() => import("./ERPRecordFilters"));
export const ERPRecordToolbar = lazy(() => import("./ERPRecordToolbar"));
export const ERPRecordHeader = lazy(() => import("./ERPRecordHeader"));
export const ERPRecordStatusBar = lazy(() => import("./ERPRecordStatusBar"));
export const ERPRecordGridView = lazy(() => import("./ERPRecordGridView"));
export const ERPRecordListView = lazy(() => import("./ERPRecordListView"));
export const ERPRecordBasicInfo = lazy(() => import("./ERPRecordBasicInfo"));
export const ERPRecordContractInfo = lazy(() => import("./ERPRecordContractInfo"));
export const ERPRecordWorkContent = lazy(() => import("./ERPRecordWorkContent"));
export const ERPRecordStatusCase = lazy(() => import("./ERPRecordStatusCase"));
export const ERPRecordDocumentSections = lazy(() => import("./ERPRecordDocumentSections"));
export const ERPContractDetailsModal = lazy(() => import("./ERPContractDetailsModal"));
export const ERPDeleteConfirmModal = lazy(() => import("./ERPDeleteConfirmModal"));
export const ERPAIAnalysisModal = lazy(() => import("./ERPAIAnalysisModal"));
export const ERPChatModals = lazy(() => import("./ERPChatModals"));
export const ERPProfileEditModal = lazy(() => import("./ERPProfileEditModal"));
export const ERPMeetingRoomModals = lazy(() => import("./ERPMeetingRoomModals"));
export const QRProfileManager = lazy(() => import("../QRProfileManager"));
export const LegalDocumentsManager = lazy(() => import("../LegalDocumentsManager"));
export const ToolsPage = lazy(() => import("../ToolsPage"));
export const SupervisionDashboard = lazy(() => import("../SupervisionDashboard"));
export const ExecutiveDashboard = lazy(() => import("../ExecutiveDashboard"));
export const SecurityView = lazy(() => import("../SecurityView"));
export const CccdOcrScanner = lazy(() => import("../CccdOcrScanner"));
export const FinanceManagementView = lazy(() => import("../FinanceManagementView"));
export const ConsultationCenter = lazy(() => import("../ConsultationCenter"));
export const CallCenterAnalytics = lazy(() => import("../CallCenterAnalytics"));
export const KenhChatView = lazy(() => import("../KenhChatView"));
export const AITrainingStudio = lazy(() => import("../AITrainingStudio").then(m => ({ default: m.AITrainingStudio })));
export const VideoMeetingModal = lazy(() => import("../VideoMeetingModal").then(m => ({ default: m.VideoMeetingModal })));
export const IotSmartGateway = lazy(() => import("../IotSmartGateway").then(m => ({ default: m.IotSmartGateway })));
export const GlobalSearch = lazy(() => import("../GlobalSearch").then(m => ({ default: m.GlobalSearch })));
export const SyncStatusDashboard = lazy(() => import("../SyncStatusDashboard").then(m => ({ default: m.SyncStatusDashboard })));
export const CompanySettingsView = lazy(() => import("../CompanySettingsView"));
export const ErpLegalMeetingWorkspace = lazy(() => import("../ErpLegalMeetingWorkspace"));
export const MemoryMonitorView = lazy(() => import("../MemoryMonitorView"));
export const LiveChatModal = lazy(() => import("../LiveChatModal"));
export const InternalChatModal = lazy(() => import("../InternalChatModal"));
